import { useState } from 'react'
import type { AesInput, AesResult } from '../contracts'
import { toHex } from '../core/encoding'
import { invoke } from '../lib/host'
import { useOperation } from '../lib/operation'
import { CopyButton, Editor, ErrorMessage, ToolHeader } from './shared'
export function AesTool() {
  const [options, setOptions] = useState<AesInput>({ operation: 'encrypt', mode: 'GCM', input: '', key: '', keyEncoding: 'hex', iv: '', ivEncoding: 'hex', outputEncoding: 'base64' })
  const [autoIv, setAutoIv] = useState(true), [showKey, setShowKey] = useState(false)
  const task = useOperation<AesResult>()
  function change(patch: Partial<AesInput>) { task.clear(); setOptions(value => ({ ...value, ...patch })) }
  const encrypt = options.operation === 'encrypt'
  return <><ToolHeader title="AES 加解密" description="使用原始密钥加解密文本，支持 GCM 和 CBC。"><button onClick={() => { change({ input: '', key: '', iv: '' }); setShowKey(false) }}>清空内容与密钥</button></ToolHeader>
    <div className="aes-options"><div className="segmented" aria-label="AES 操作">{(['encrypt','decrypt'] as const).map(operation => <button key={operation} aria-pressed={options.operation === operation} onClick={() => change({ operation })}>{operation === 'encrypt' ? '加密' : '解密'}</button>)}</div><label className="inline-field">模式<select value={options.mode} onChange={e => change({ mode: e.target.value as AesInput['mode'], iv: '' })}><option value="GCM">AES-GCM（推荐）</option><option value="CBC">AES-CBC</option></select></label><label className="inline-field">密文编码<select value={options.outputEncoding} onChange={e => change({ outputEncoding: e.target.value as AesInput['outputEncoding'] })}><option value="base64">Base64</option><option value="hex">Hex</option></select></label></div>
    <div className="key-grid"><label className="field">密钥编码<select value={options.keyEncoding} onChange={e => change({ keyEncoding: e.target.value as AesInput['keyEncoding'] })}><option value="hex">Hex</option><option value="base64">Base64</option><option value="utf8">UTF-8</option></select></label><label className="field grow">密钥<input type={showKey ? 'text' : 'password'} value={options.key} onChange={e => change({ key: e.target.value })} autoComplete="off" spellCheck={false} placeholder="输入 16、24 或 32 字节密钥" /></label><div className="key-buttons"><button aria-pressed={showKey} onClick={() => setShowKey(!showKey)}>{showKey ? '隐藏' : '显示'}</button><button className="bordered" onClick={() => { change({ key: toHex(crypto.getRandomValues(new Uint8Array(32))), keyEncoding: 'hex' }); setShowKey(true) }}>生成密钥</button><CopyButton value={options.key} disabled={!options.key} label="复制密钥" /></div></div>
    <div className="iv-options">{encrypt && <label className="check"><input type="checkbox" checked={autoIv} onChange={e => { task.clear(); setAutoIv(e.target.checked) }} />每次自动生成 IV</label>}{(!encrypt || !autoIv) && <div className="iv-fields"><label className="field">IV 编码<select value={options.ivEncoding} onChange={e => change({ ivEncoding: e.target.value as AesInput['ivEncoding'] })}><option value="hex">Hex</option><option value="base64">Base64</option></select></label><label className="field grow">IV（{options.mode === 'GCM' ? 12 : 16} 字节）<input value={options.iv} onChange={e => change({ iv: e.target.value })} autoComplete="off" placeholder="填入加密时使用的 IV" /></label></div>}</div>
    <div className="editors aes-editors"><Editor label={encrypt ? '待加密文本' : '待解密密文'} value={options.input} onChange={input => change({ input })} placeholder={encrypt ? '输入需要加密的 UTF-8 文本' : '粘贴密文（与上方密文编码一致）'} /><Editor label={encrypt ? '加密结果' : '解密结果'} value={task.result?.text || ''} readOnly placeholder="结果显示在这里" actions={<CopyButton value={task.result?.text || ''} disabled={!task.result} />} /></div>
    <div className="action-row"><button className="primary" disabled={task.busy || !options.key} onClick={() => void task.run(() => invoke('aes.process', { ...options, iv: encrypt && autoIv ? '' : options.iv }))}>{task.busy ? '处理中…' : encrypt ? '加密文本' : '解密文本'}</button>{task.result && encrypt && <button className="bordered" onClick={() => change({ operation: 'decrypt', input: task.result!.text, iv: task.result!.iv, ivEncoding: task.result!.ivEncoding })}>用此结果解密</button>}</div>
    <ErrorMessage error={task.error} />{task.result && <div className="iv-result"><span>本次 IV · {task.result.ivEncoding}</span><code>{task.result.iv}</code><CopyButton value={task.result.iv} label="复制 IV" /></div>}
    <p className="hint">{options.mode === 'GCM' ? 'GCM 密文末尾包含 16 字节认证标签。相同密钥下请勿重复使用 IV。' : 'CBC 使用 PKCS#7 填充，不包含认证标签。'} 解密需要保存密钥和 IV；这里的密钥不是自动派生的密码。</p>
  </>
}
