import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'
import manifest from '../app.moss.json' with { type: 'json' }
import { installHostFixture } from './host-fixture'
import { BUILTIN_SERVERS } from '../src/builtins'
const screenshots = path.resolve(import.meta.dirname, '../../..', `artifacts/moss.mcp/screenshots/${manifest.version}`)

test('connection management supports adding, validation, editing, toggling and deletion', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '搜索工具' }).fill('tokens')
  await expect(page.getByRole('heading', { name: 'get_design_tokens' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'search_components' })).toHaveCount(0)
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '添加 MCP 服务' })
  await dialog.getByLabel('服务名称').fill('new-service')
  await dialog.getByLabel('服务地址').fill('not-a-url')
  await dialog.getByRole('button', { name: '创建连接', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('有效')
  await dialog.getByLabel('服务地址').fill('https://example.com/mcp')
  await dialog.getByRole('button', { name: '添加请求头' }).click()
  await dialog.getByLabel('请求头名称 1').fill('Authorization')
  await dialog.getByLabel('请求头值 1').fill('Bearer browser-fixture')
  await dialog.getByRole('button', { name: '创建连接', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'new-service', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '连接配置', exact: true }).click()
  await expect(page.getByText('Authorization', { exact: true })).toBeVisible()
  await expect(page.getByText('Bearer browser-fixture', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '编辑连接', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '编辑连接' })
  await expect(edit.getByLabel('请求头值 1')).toHaveValue('')
  await edit.getByLabel('服务名称').fill('renamed-service')
  await edit.getByRole('button', { name: '保存更改' }).click()
  await expect(edit).toHaveCount(0)
  await page.getByRole('switch', { name: '启用 renamed-service' }).click()
  await expect(page.getByRole('switch', { name: '启用 renamed-service' })).toHaveAttribute('aria-checked', 'false')
  await page.getByRole('button', { name: '删除连接', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '删除连接', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'renamed-service' })).toHaveCount(0)
  expect(errors).toEqual([])
})

for (const theme of ['light', 'dark'] as const) test(`${theme}: renders Moss surfaces, responsive layout, and accessible editor`, async ({ page }) => {
  await page.emulateMedia({ colorScheme: theme })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: path.join(screenshots, `${theme}.png`), fullPage: true })
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  await page.getByRole('button', { name: '本地进程 命令行启动' }).click()
  await expect(page.getByLabel('启动命令')).toBeVisible()
  await page.screenshot({ path: path.join(screenshots, `${theme}-editor.png`), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  for (const width of [760, 600, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.detail-pane').evaluate(el => el.getBoundingClientRect().right <= innerWidth)).toBe(true)
    expect(await page.locator('.detail-pane').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await expect(page.getByRole('button', { name: '检查连接', exact: true })).toBeInViewport()
    await expect(page.getByRole('button', { name: '添加服务', exact: true })).toBeInViewport()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, `${theme}-narrow.png`), fullPage: true })
})

test('search and filter empty states keep the primary action available', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '搜索服务' }).fill('no-matching-connection')
  await expect(page.getByRole('heading', { name: '没有匹配的服务' })).toBeVisible()
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '清除筛选' }).click()
  await page.getByRole('button', { name: '已停用', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'legacy-search', exact: true })).toBeVisible()
  await expect(page.getByRole('switch', { name: '启用 legacy-search' })).toHaveAttribute('aria-checked', 'false')
})

test('initial loading, first creation and last deletion use one add entry', async ({ page }) => {
  const fixture = await installHostFixture(page, { holdInitialList: true })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '正在加载连接' })).toBeVisible()
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '添加你的第一个 MCP 服务' })).toHaveCount(0)
  fixture.releaseList()
  await expect(page.getByRole('heading', { name: '添加你的第一个 MCP 服务' })).toBeVisible()
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(1)
  await expect(page.getByRole('textbox', { name: '搜索服务' })).toHaveCount(0)
  await expect(page.getByRole('complementary')).toHaveCount(0)
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '添加 MCP 服务' })
  await dialog.getByLabel('服务名称').fill('first-service')
  await dialog.getByLabel('服务地址').fill('https://example.com/mcp')
  await dialog.getByRole('button', { name: '创建连接' }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'first-service', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: '服务连接', exact: true })).toBeVisible()
  await expect(page.getByRole('complementary')).toBeVisible()
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(1)
  fixture.failNextList()
  await page.getByRole('button', { name: '刷新服务列表' }).click()
  await expect(page.getByRole('alert')).toContainText('无法读取连接')
  await expect(page.getByRole('heading', { name: 'first-service', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '删除连接', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '删除连接', exact: true }).click()
  await expect(page.getByRole('heading', { name: '添加你的第一个 MCP 服务' })).toBeVisible()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(1)
  await expect(page.getByRole('complementary')).toHaveCount(0)
})

test('initial loading failure offers retry instead of the first-service guide', async ({ page }) => {
  await installHostFixture(page, { failInitialList: true })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '连接列表加载失败' })).toBeVisible()
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: '搜索服务' })).toHaveCount(0)
  await page.getByRole('button', { name: '重新加载' }).click()
  await expect(page.getByRole('heading', { name: '添加你的第一个 MCP 服务' })).toBeVisible()
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(1)
})

for (const theme of ['light', 'dark'] as const) test(`${theme}: empty Host catalog stays compact at narrow and short viewport sizes`, async ({ page }) => {
  await installHostFixture(page)
  await page.emulateMedia({ colorScheme: theme })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '添加你的第一个 MCP 服务' })).toBeVisible()
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: path.join(screenshots, `${theme}-empty.png`), fullPage: true })
  for (const [width, height] of [[1280, 480], [760, 500], [390, 640], [320, 568]]) {
    await page.setViewportSize({ width, height })
    await expect(page.getByRole('button', { name: '添加服务', exact: true })).toHaveCount(1)
    await expect(page.getByRole('button', { name: '添加服务', exact: true })).toBeInViewport({ ratio: 1 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 640 })
  await page.screenshot({ path: path.join(screenshots, `${theme}-empty-narrow.png`), fullPage: true })
})

test('short desktop window keeps the toolbar and dialog submit action visible', async ({ page }) => {
  await page.setViewportSize({ width: 1120, height: 420 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= innerHeight)).toBe(true)
  await expect(page.getByRole('button', { name: '添加服务', exact: true })).toBeInViewport({ ratio: 1 })
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByRole('button', { name: '创建连接' })).toBeInViewport({ ratio: 1 })
  await dialog.getByRole('button', { name: '本地进程 命令行启动' }).click()
  await dialog.getByText('高级选项', { exact: false }).click()
  await expect(dialog.getByRole('button', { name: '创建连接' })).toBeInViewport({ ratio: 1 })
  await dialog.getByLabel('不启用的工具').fill('hidden-tool')
  await expect(dialog.getByRole('button', { name: '创建连接' })).toBeInViewport({ ratio: 1 })
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})


test('built-in browser service shows portable settings and can be edited and disabled', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('navigation', { name: '服务列表' }).getByRole('button', { name: /playwright-cdp/ }).click()
  await expect(page.getByRole('heading', { name: '服务连接', exact: true })).toBeVisible()
  await expect(page.getByText('工具与连接', { exact: true })).toHaveCount(0)
  await expect(page.getByText('MCP 让工具融入对话', { exact: true })).toHaveCount(0)
  await expect(page.locator('.builtin-badge')).toHaveText('内置')
  await expect(page.getByRole('button', { name: '删除连接', exact: true })).toHaveCount(0)
  await page.getByRole('tab', { name: '连接配置', exact: true }).click()
  await expect(page.getByText('~/.moss/artifacts/playwright', { exact: true })).toBeVisible()
  await expect(page.getByText(/本机 CDP 未开启时会自动启动系统 Chrome/)).toBeVisible()
  await page.screenshot({ path: path.join(screenshots, 'builtin-config.png'), fullPage: true })
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.getByRole('button', { name: '编辑连接', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '编辑连接' })
  await expect(edit.getByLabel('服务名称')).toHaveAttribute('readonly', '')
  await expect(edit.getByLabel('启动命令')).toHaveCount(0)
  await expect(edit.getByText(/无需安装 Node.js、npm 或联网下载/)).toBeVisible()
  await edit.getByLabel('启动参数').fill('--cdp-endpoint\nhttp://127.0.0.1:9444\n--output-dir\n~/Browser Artifacts')
  await edit.getByRole('button', { name: '保存更改' }).click()
  await expect(edit).toHaveCount(0)
  await page.getByRole('tab', { name: '连接配置', exact: true }).click()
  await expect(page.getByText('~/Browser Artifacts', { exact: true })).toBeVisible()
  await page.getByRole('switch', { name: '启用 playwright-cdp' }).click()
  await expect(page.getByRole('switch', { name: '启用 playwright-cdp' })).toHaveAttribute('aria-checked', 'false')
  await page.getByRole('button', { name: '刷新服务列表' }).click()
  await expect(page.getByRole('switch', { name: '启用 playwright-cdp' })).toHaveAttribute('aria-checked', 'false')
})


test('browser startup failure shows a useful explanation, configuration action, and retry', async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: BUILTIN_SERVERS.map(server => ({ ...server, updatedAt: Date.now() })), inspectError: '未找到系统 Chrome。请安装 Chrome，或在启动参数中通过 --executable-path 指定路径。' })
  await page.goto('/')
  await page.getByRole('tab', { name: '连接配置', exact: true }).click()
  await page.getByRole('button', { name: '检查连接', exact: true }).click()
  await expect(page.getByRole('tab', { name: '可用工具' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('alert')).toContainText('未找到系统 Chrome')
  await page.screenshot({ path: path.join(screenshots, 'browser-startup-error.png'), fullPage: true })
  await page.getByRole('button', { name: '修改浏览器配置', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '编辑连接' }).getByLabel('启动参数')).toBeVisible()
  await page.keyboard.press('Escape')
  fixture.recoverInspection()
  await page.locator('.check-actions').getByRole('button', { name: '检查连接', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '工具目录' })).toBeVisible()
})

const browserTools = [
  { name: 'browser_navigate', description: 'Navigate to a URL', disabled: false },
  { name: 'browser_click', description: 'Click an element', disabled: false },
]
const browserServers = () => BUILTIN_SERVERS.map(server => ({ ...server, updatedAt: 1 }))

test('first opening discovers tools automatically and preserves the selected tab', async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: browserServers(), tools: browserTools, holdInspection: true })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '正在加载工具目录' })).toBeVisible()
  await page.getByRole('tab', { name: '连接配置' }).click()
  fixture.releaseInspection()
  await expect(page.locator('.check-actions').getByRole('button', { name: '检查连接' })).toBeVisible()
  await expect(page.getByRole('tab', { name: '连接配置' })).toHaveAttribute('aria-selected', 'true')
  await page.getByRole('tab', { name: '可用工具' }).click()
  await expect(page.getByRole('heading', { name: 'browser_navigate', exact: true })).toBeVisible()
  expect(fixture.calls.filter(method => method === 'servers.inspect')).toHaveLength(1)
})

test('enabling and editing a service both automatically reload its tools', async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: browserServers().map(server => ({ ...server, enabled: false })), tools: browserTools })
  await page.goto('/')
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  expect(fixture.calls).not.toContain('servers.inspect')
  await page.getByRole('switch').click()
  await expect(page.getByRole('heading', { name: 'browser_click', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '编辑连接', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '编辑连接' })
  await edit.getByText('高级选项', { exact: false }).click()
  await edit.getByLabel('不启用的工具').fill('browser_click')
  await edit.getByRole('button', { name: '保存更改' }).click()
  await expect(page.getByRole('heading', { name: /browser_click.*已排除/ })).toBeVisible()
  expect(fixture.calls.filter(method => method === 'servers.inspect')).toHaveLength(2)
})

test('disabling during discovery ignores the late tool response', async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: browserServers(), tools: browserTools, holdInspection: true })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '正在加载工具目录' })).toBeVisible()
  await page.getByRole('switch').click()
  await expect(page.getByRole('switch')).toHaveAttribute('aria-checked', 'false')
  fixture.releaseInspection()
  await expect.poll(fixture.cancellations).toBeGreaterThan(0)
  await expect(page.getByRole('heading', { name: 'browser_click', exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: '正在加载工具目录' })).toHaveCount(0)
  await page.getByRole('switch').click()
  await expect(page.getByRole('heading', { name: 'browser_click', exact: true })).toBeVisible()
})

test('cancelled automatic discovery can be retried manually', async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: browserServers(), tools: browserTools, holdInspection: true })
  await page.goto('/')
  await page.getByRole('button', { name: /加载工具中.*取消/ }).click()
  fixture.releaseInspection()
  await expect(page.getByRole('alert')).toContainText('已取消')
  await page.locator('.check-actions').getByRole('button', { name: '检查连接', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'browser_click', exact: true })).toBeVisible()
})

test('a stale discovery response shows an actionable error instead of spinning forever', async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: browserServers(), tools: browserTools, staleInspection: true })
  await page.goto('/')
  await expect(page.getByRole('alert')).toContainText('连接配置已变化')
  await expect(page.getByRole('heading', { name: '正在加载工具目录' })).toHaveCount(0)
  expect(fixture.calls.filter(method => method === 'servers.inspect')).toHaveLength(1)
})

for (const state of ['needs-auth', 'connected', 'failed'] as const) test(`does not automatically re-inspect a ${state} service`, async ({ page }) => {
  const fixture = await installHostFixture(page, { servers: browserServers().map(server => ({ ...server, check: { state, tools: [], checkedAt: 1 } })) })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'playwright-cdp', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '连接配置' }).click()
  await page.getByRole('tab', { name: '可用工具' }).click()
  expect(fixture.calls).not.toContain('servers.inspect')
})
