import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import path from 'node:path'
const screenshots = path.resolve(import.meta.dirname, '../../..', 'artifacts/moss.mcp/screenshots/0.1.0')

test('connection management supports adding, validation, editing, toggling and deletion', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '搜索工具' }).fill('tokens')
  await expect(page.getByRole('heading', { name: 'get_design_tokens' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'search_components' })).toHaveCount(0)
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '添加 MCP 服务' })
  await dialog.getByLabel('服务名称').fill('new-service')
  await dialog.getByLabel('服务地址').fill('not-a-url')
  await dialog.getByRole('button', { name: '添加服务', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('有效')
  await dialog.getByLabel('服务地址').fill('https://example.com/mcp')
  await dialog.getByRole('button', { name: '添加请求头' }).click()
  await dialog.getByLabel('请求头名称 1').fill('Authorization')
  await dialog.getByLabel('请求头值 1').fill('Bearer browser-fixture')
  await dialog.getByRole('button', { name: '添加服务', exact: true }).click()
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'new-service', exact: true })).toBeVisible()
  await page.getByRole('tab', { name: '连接配置', exact: true }).click()
  await expect(page.getByText('Authorization', { exact: true })).toBeVisible()
  await expect(page.getByText('Bearer browser-fixture', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '编辑连接', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '编辑连接' })
  await expect(edit.getByLabel('请求头值 1')).toHaveValue('')
  await edit.getByLabel('服务名称').fill('renamed-service')
  await edit.getByRole('button', { name: '保存更改' }).click()
  await expect(edit).toHaveCount(0)
  await page.getByRole('switch', { name: '启用 renamed-service' }).click()
  await expect(page.getByRole('switch', { name: '启用 renamed-service' })).toHaveAttribute('aria-checked', 'false')
  await page.getByRole('button', { name: '删除连接', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '删除连接', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'renamed-service' })).toHaveCount(0)
  expect(errors).toEqual([])
})

for (const theme of ['light', 'dark'] as const) test(`${theme}: renders Moss surfaces, responsive layout, and accessible editor`, async ({ page }) => {
  await page.emulateMedia({ colorScheme: theme })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
  await mkdir(screenshots, { recursive: true })
  await page.screenshot({ path: path.join(screenshots, `${theme}.png`), fullPage: true })
  await page.getByRole('button', { name: '添加服务', exact: true }).click()
  await page.getByRole('button', { name: '本地进程 命令行启动' }).click()
  await expect(page.getByLabel('启动命令')).toBeVisible()
  await page.screenshot({ path: path.join(screenshots, `${theme}-editor.png`), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  for (const width of [760, 600, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect(await page.locator('.detail-pane').evaluate(el => el.getBoundingClientRect().right <= innerWidth)).toBe(true)
    expect(await page.locator('.detail-pane').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await expect(page.getByRole('button', { name: '检查连接', exact: true })).toBeInViewport()
    await expect(page.getByRole('button', { name: '添加服务', exact: true })).toBeInViewport()
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, `${theme}-narrow.png`), fullPage: true })
})

test('search and filter empty states keep the primary action available', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'design-library', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: '搜索服务' }).fill('no-matching-connection')
  await expect(page.getByRole('heading', { name: '没有匹配的服务' })).toBeVisible()
  await page.getByRole('button', { name: '清除筛选' }).click()
  await page.getByRole('button', { name: '已停用', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'legacy-search', exact: true })).toBeVisible()
  await expect(page.getByRole('switch', { name: '启用 legacy-search' })).toHaveAttribute('aria-checked', 'false')
})
